const state = {
    images: [],
    options: {
        makeModels: [
            {
                make: "toyota",
                models: [
                    "4runner",
                    "86",
                    "allex",
                    "allion",
                    "alphard",
                    "alphard hybrid",
                    "altezza",
                    "altezza gita",
                    "aqua",
                    "aristo",
                    "auris",
                    "avalon",
                    "avanza",
                    "avensis",
                    "avensis wagon",
                    "aygo",
                    "bb",
                    "belta",
                    "blade",
                    "brevis",
                    "c-hr",
                    "caldina",
                    "caldina van",
                    "cami",
                    "camry",
                    "carina",
                    "celica",
                    "celsior",
                    "century",
                    "chaser",
                    "coaster",
                    "corolla",
                    "corolla altis",
                    "corolla axio",
                    "corolla fielder",
                    "corolla levin",
                    "corolla rumion",
                    "corolla runx",
                    "corolla spacio",
                    "corolla sport",
                    "corolla touring",
                    "corolla van",
                    "corolla verso",
                    "corona",
                    "corona premio",
                    "cresta",
                    "crown",
                    "crown comfort",
                    "crown estate",
                    "crown hybrid",
                    "crown majesta",
                    "crown wagon",
                    "cynos",
                    "dyna",
                    "esquire",
                    "estima",
                    "estima hybrid",
                    "fj cruiser",
                    "fork lift",
                    "forklift",
                    "fortuner",
                    "funcargo",
                    "gaia",
                    "granace",
                    "grand hiace",
                    "granvia",
                    "harrier",
                    "harrier hybrid",
                    "hiace commuter",
                    "hiace regius",
                    "hiace truck",
                    "hiace van",
                    "hiace wagon",
                    "highlander",
                    "hilux",
                    "hilux surf",
                    "ipsum",
                    "iq",
                    "isis",
                    "ist",
                    "kluger",
                    "kluger hybrid",
                    "land cruiser",
                    "land cruiser 100",
                    "land cruiser 60",
                    "land cruiser 70",
                    "land cruiser 80",
                    "land cruiser prado",
                    "liteace",
                    "liteace noah",
                    "liteace truck",
                    "majesta",
                    "mark ii",
                    "mark ii blit",
                    "mark x",
                    "mark x zio",
                    "mr2",
                    "mrs",
                    "nadia",
                    "noah",
                    "opa",
                    "origin",
                    "passo",
                    "passo sette",
                    "pixis",
                    "pixis epoch",
                    "pixis joy",
                    "pixis mega",
                    "pixis space",
                    "pixis truck",
                    "pixis van",
                    "platz",
                    "porte",
                    "premio",
                    "previa",
                    "prius",
                    "prius alpha",
                    "prius phv",
                    "proace",
                    "probox van",
                    "probox wagon",
                    "progres",
                    "ractis",
                    "raize",
                    "raum",
                    "rav4",
                    "regius",
                    "regiusace commuter",
                    "regiusace van",
                    "roomy",
                    "rush",
                    "sai",
                    "sequoia",
                    "sienna",
                    "sienta",
                    "soarer",
                    "spade",
                    "sprinter",
                    "sprinter trueno",
                    "starlet",
                    "succeed van",
                    "succeed wagon",
                    "supra",
                    "tank",
                    "townace",
                    "townace noah",
                    "townace truck",
                    "townace wagon",
                    "toyoace truck",
                    "toyota",
                    "tundra",
                    "vanguard",
                    "vellfire",
                    "vellfire hybrid",
                    "venza",
                    "verossa",
                    "verso",
                    "vios",
                    "vista ardeo",
                    "vitz",
                    "voltz",
                    "voxy",
                    "will cypha",
                    "will vi",
                    "windom",
                    "wish",
                    "yaris"
                ]
            },
            {
                make: "nissan",
                models: [
                    "180sx",
                    "ad",
                    "ad expert",
                    "ad max van",
                    "ad van",
                    "almera",
                    "altima",
                    "atlas truck",
                    "big thumb",
                    "bluebird",
                    "bluebird sylphy",
                    "cabstar",
                    "caravan",
                    "caravan bus",
                    "caravan coach",
                    "cedric",
                    "cedric van",
                    "cedric wagon",
                    "cefiro",
                    "cima",
                    "civilian",
                    "clipper rio",
                    "clipper truck",
                    "clipper van",
                    "condor",
                    "crew",
                    "cube",
                    "cube cubic",
                    "datsun",
                    "dayz",
                    "dayz roox",
                    "dualis",
                    "elgrand",
                    "env200van",
                    "fairlady z",
                    "fuga",
                    "fuga hybrid",
                    "gloria",
                    "gloria van",
                    "gt-r",
                    "homy van",
                    "infiniti q45",
                    "juke",
                    "kix",
                    "lafesta",
                    "latio",
                    "laurel",
                    "leaf",
                    "liberty",
                    "march",
                    "maxima",
                    "micra",
                    "micra cc",
                    "moco",
                    "murano",
                    "navara",
                    "nissan",
                    "nissan ud",
                    "note",
                    "np300",
                    "nt100clipper",
                    "nv100clipper",
                    "nv100clipper rio",
                    "nv150 ad",
                    "nv200 wagon",
                    "nv200vanette van",
                    "nv200vanette wagon",
                    "nv350caravan",
                    "nv350caravan wagon",
                    "otti",
                    "pao",
                    "pathfinder",
                    "patrol",
                    "pino",
                    "presage",
                    "president",
                    "primera",
                    "pulsar",
                    "qashqai",
                    "qashqai+2",
                    "rasheen",
                    "rogue",
                    "roox",
                    "safari",
                    "serena",
                    "silvia",
                    "skyline",
                    "skyline crossover",
                    "spacerunner rm",
                    "stagea",
                    "sunny",
                    "sylphy",
                    "sylphy ev",
                    "teana",
                    "terrano",
                    "tiida",
                    "tiida latio",
                    "vanette",
                    "vanette truck",
                    "vanette van",
                    "wingroad",
                    "xtrail"
                ]
            },
            {
                make: "honda",
                models: [
                    "accord",
                    "accord hybrid",
                    "accord tourer",
                    "acty truck",
                    "acty van",
                    "airwave",
                    "atv",
                    "beat",
                    "city",
                    "civic",
                    "civic ferio",
                    "civic hybrid",
                    "cross road",
                    "crv",
                    "crx",
                    "crx delsol",
                    "crz",
                    "edix",
                    "element",
                    "elysion",
                    "elysion prestige",
                    "fit",
                    "fit aria",
                    "fit hybrid",
                    "fit shuttle",
                    "fit shuttle hybrid",
                    "freed",
                    "freed hybrid",
                    "freed spike",
                    "freed spike hybrid",
                    "freed+",
                    "freed+ hybrid",
                    "grace",
                    "hr-v",
                    "insight",
                    "inspire",
                    "integra",
                    "jade",
                    "jazz",
                    "lagreat",
                    "legend",
                    "life",
                    "mobilio",
                    "mobilio spike",
                    "n box",
                    "n box custom",
                    "n box plus",
                    "n box plus custom",
                    "n box slash",
                    "n one",
                    "n van",
                    "nsx",
                    "nwgn",
                    "nwgn custom",
                    "odyssey",
                    "pilot",
                    "prelude",
                    "s2000",
                    "s660",
                    "shuttle",
                    "smx",
                    "stepwagon",
                    "stepwagon spada",
                    "stream",
                    "thats",
                    "torneo",
                    "vamos",
                    "vamos hobio",
                    "vezel",
                    "zest",
                    "zest spark"
                ]
            },
            {
                make: "suzuki",
                models: [
                    "alto",
                    "alto eco",
                    "alto lapin",
                    "alto lapin chocolat",
                    "alto works",
                    "baleno",
                    "cappuccino",
                    "cara",
                    "carry truck",
                    "cervo",
                    "escudo",
                    "every",
                    "every wagon",
                    "grand vitara",
                    "hustler",
                    "ignis",
                    "jimny",
                    "jimny sierra",
                    "jimny wide",
                    "kei",
                    "kizashi",
                    "landy",
                    "mr wagon",
                    "mr wagon wit",
                    "palette",
                    "solio",
                    "solio bandit",
                    "spacia",
                    "spacia custom",
                    "spacia gear",
                    "splash",
                    "swift",
                    "swift sport",
                    "sx4",
                    "sx4 sedan",
                    "twin",
                    "vitra",
                    "wagon r",
                    "wagon r solio",
                    "wagon r stingray",
                    "xbee"
                ]
            },
            {
                make: "mazda",
                models: [
                    "2",
                    "3",
                    "5",
                    "6",
                    "atenza",
                    "atenza sport",
                    "atenza sport wagon",
                    "atenza wagon",
                    "axela",
                    "axela hybrid",
                    "axela sport",
                    "az wagon",
                    "az-1",
                    "azoffroad",
                    "biante",
                    "bongo",
                    "bongo brawny van",
                    "bongo truck",
                    "bongo van",
                    "carol",
                    "cx-30",
                    "cx3",
                    "cx5",
                    "cx7",
                    "cx8",
                    "demio",
                    "familia",
                    "familia s wagon",
                    "familia van",
                    "familia wagon",
                    "flair",
                    "flair crossover",
                    "flair custom style",
                    "flair wagon",
                    "luce",
                    "mazda2",
                    "mazda3",
                    "mazda3 fastback",
                    "mazda6",
                    "mazda6 wagon",
                    "mazda8",
                    "mpv",
                    "premacy",
                    "proceed",
                    "proceed marvie",
                    "roadster",
                    "rx7",
                    "rx8",
                    "savanna rx7",
                    "scrum",
                    "scrum truck",
                    "scrum wagon",
                    "spiano",
                    "titan",
                    "tribute",
                    "verisa"
                ]
            },
            {
                make: "daihatsu",
                models: [
                    "altis",
                    "atrai",
                    "atrai 7",
                    "atrai wagon",
                    "bego",
                    "boon",
                    "cast",
                    "coo",
                    "copen",
                    "delta truck",
                    "esse",
                    "hijet caddie",
                    "hijet cargo",
                    "hijet truck",
                    "hijet van",
                    "max",
                    "midgetii",
                    "mira",
                    "mira avy",
                    "mira cocoa",
                    "mira custom",
                    "mira es",
                    "mira gino",
                    "mira gino 1000",
                    "mira tocot",
                    "move",
                    "move canbus",
                    "move conte",
                    "move latte",
                    "naked",
                    "opti",
                    "rocky",
                    "rugger",
                    "sonica",
                    "tanto",
                    "tanto exe",
                    "terios",
                    "terios kid",
                    "thor",
                    "wake",
                    "yrv"
                ]
            },
            {
                make: "mitsubishi",
                models: [
                    "aero bus",
                    "aero midi",
                    "aero star",
                    "airtrek",
                    "asx",
                    "attrage",
                    "canter guts",
                    "canter truck",
                    "chariot grandis",
                    "colt",
                    "colt plus",
                    "delica",
                    "delica d2",
                    "delica d5",
                    "delica space gear",
                    "delica truck",
                    "delica van",
                    "eclipse",
                    "eclipse cross",
                    "ek cross",
                    "ek custom",
                    "ek space",
                    "ek space custom",
                    "ek sport",
                    "ek wagon",
                    "fighter",
                    "galant fortis",
                    "grandis",
                    "great",
                    "gto",
                    "i",
                    "jeep",
                    "l200",
                    "lancer",
                    "lancer cargo",
                    "lancer van",
                    "lancer wagon",
                    "legnum",
                    "minica",
                    "minicab",
                    "minicab truck",
                    "minicab van",
                    "mirage",
                    "outlander",
                    "outlander phev",
                    "pajero",
                    "pajero io",
                    "pajero jr",
                    "pajero mini",
                    "rosa",
                    "rvr",
                    "shogun",
                    "super great",
                    "toppo",
                    "toppo bj",
                    "town box",
                    "triton"
                ]
            },
            {
                make: "subaru",
                models: [
                    "brz",
                    "chiffon",
                    "dex",
                    "dias wagon",
                    "exiga",
                    "exiga crossover 7",
                    "forester",
                    "impreza",
                    "impreza anesis",
                    "impreza sports",
                    "impreza sports wagon",
                    "impreza xv",
                    "impreza xv hybrid",
                    "justy",
                    "legacy",
                    "legacy b4",
                    "legacy lancaster",
                    "legacy outback",
                    "legacy touring wagon",
                    "levorg",
                    "lucra",
                    "outback",
                    "pleo",
                    "pleo plus",
                    "r1",
                    "r2",
                    "sambar",
                    "sambar dias",
                    "sambar truck",
                    "stella",
                    "trezia",
                    "vivio",
                    "wrx",
                    "wrx s4",
                    "wrx sti",
                    "xv"
                ]
            },
            {
                make: "bmw",
                models: [
                    "1 series",
                    "2 series",
                    "3 series",
                    "4 series",
                    "5 series",
                    "6 series",
                    "7 series",
                    "8 series",
                    "bmw",
                    "i3",
                    "i8",
                    "m roadster",
                    "m2",
                    "m3",
                    "m4",
                    "m5",
                    "m6",
                    "mini",
                    "x1",
                    "x2",
                    "x3",
                    "x4",
                    "x5",
                    "x5m",
                    "x6",
                    "z3",
                    "z4"
                ]
            },
            {
                make: "mercedes",
                models: [
                    "190 class",
                    "a class",
                    "actros",
                    "atego",
                    "axor",
                    "b class",
                    "c class",
                    "c class stationwagon",
                    "citan 109",
                    "cl class",
                    "cla class",
                    "cla class shootingbrake",
                    "clk class",
                    "cls class",
                    "cls class shootingbrake",
                    "e class",
                    "e class stationwagon",
                    "g class",
                    "gl class",
                    "gla class",
                    "glc class",
                    "gle class",
                    "glk class",
                    "gls class",
                    "m class",
                    "medium class",
                    "mercedes (truck)",
                    "r class",
                    "s class",
                    "sl class",
                    "slc class",
                    "slk class",
                    "sprinter",
                    "v class",
                    "viano",
                    "vito"
                ]
            },
            {
                make: "lexus",
                models: [
                    "ct",
                    "ct200h",
                    "es",
                    "es250",
                    "gs",
                    "gs250",
                    "gs300",
                    "gs350",
                    "gs450h",
                    "gx460",
                    "gx470",
                    "hs",
                    "hs250h",
                    "is",
                    "is f",
                    "is300h",
                    "is350",
                    "lc500",
                    "lc500h",
                    "ls",
                    "ls400",
                    "ls460",
                    "lx",
                    "lx450",
                    "lx470",
                    "lx570",
                    "nx",
                    "nx200",
                    "nx200t",
                    "nx300",
                    "rc",
                    "rc f",
                    "rx",
                    "rx270",
                    "rx300",
                    "rx350",
                    "rx400h",
                    "rx450h",
                    "rx450hl",
                    "sc430",
                    "ux"
                ]
            },
            {
                make: "volkswagen",
                models: [
                    "amarok",
                    "arteon",
                    "beetle",
                    "caddy",
                    "cc",
                    "crafter",
                    "eos",
                    "eurovan",
                    "golf",
                    "golf cabriolet",
                    "golf gte",
                    "golf gti",
                    "golf plus",
                    "golf r",
                    "golf r variant",
                    "golf touran",
                    "golf variant",
                    "golf wagon",
                    "jetta",
                    "lupo",
                    "new beetle",
                    "new beetle cabriolet",
                    "passat",
                    "passat alltrack",
                    "passat cc",
                    "passat variant",
                    "passat variant 1",
                    "phaeton",
                    "polo",
                    "polo gti",
                    "scirocco",
                    "sharan",
                    "the beetle",
                    "the beetle cabriolet",
                    "tiguan",
                    "touareg",
                    "touran",
                    "transporter",
                    "up",
                    "vanagon",
                    "volkswagen"
                ]
            },
            {
                make: "isuzu",
                models: [
                    "bighorn",
                    "d-max",
                    "elf truck",
                    "forward",
                    "giga",
                    "journey",
                    "juston",
                    "piazza"
                ]
            },
            {
                make: "mini",
                models: [
                    "cooper",
                    "countryman",
                    "mini",
                    "mini clubman",
                    "mini convertible"
                ]
            },
            { make: "audi", models: [] },
            {
                make: "hino",
                models: [
                    "dutro",
                    "dutro hybrid",
                    "liesse",
                    "liesse ii",
                    "melpha",
                    "profia",
                    "rainbow",
                    "ranger",
                    "ranger ii",
                    "selega"
                ]
            },
            {
                make: "volvo",
                models: [
                    "c70",
                    "fh",
                    "fh12",
                    "fm12",
                    "s40",
                    "s60",
                    "s80",
                    "s90",
                    "v40",
                    "v50",
                    "v60",
                    "v70",
                    "v90",
                    "volvo",
                    "volvo (truck)",
                    "xc60",
                    "xc70",
                    "xc90"
                ]
            },
            {
                make: "peugeot",
                models: [
                    "1007",
                    "107",
                    "108",
                    "2008",
                    "206",
                    "207",
                    "208",
                    "3008",
                    "306",
                    "307",
                    "308",
                    "4007",
                    "4008",
                    "406",
                    "407",
                    "5008",
                    "508",
                    "607",
                    "partner",
                    "peugeot",
                    "rcz"
                ]
            },
            {
                make: "ford",
                models: [
                    "b-max",
                    "ecosport",
                    "edge",
                    "escape",
                    "expedition",
                    "explorer",
                    "explorer sport trac",
                    "five hundred",
                    "ford",
                    "fusion",
                    "kuga",
                    "mondeo",
                    "mustang",
                    "ranger",
                    "s-max",
                    "taurus",
                    "transit",
                    "transit connect"
                ]
            },
            {
                make: "chrysler jeep",
                models: [
                    "jeep cherokee",
                    "jeep compass",
                    "jeep grand cherokee",
                    "jeep patriot",
                    "jeep renegade",
                    "jeep wrangler",
                    "jeep wrangler unlimited"
                ]
            },
            {
                make: "land rover",
                models: [
                    "discovery",
                    "discovery 3",
                    "discovery 4",
                    "discovery sport",
                    "freelander",
                    "freelander 2",
                    "land rover",
                    "range rover",
                    "range rover evoque",
                    "range rover evoque convertible",
                    "range rover evoque coupe",
                    "range rover sport",
                    "range rover velar",
                    "range rover vogue"
                ]
            },
            {
                make: "porsche",
                models: [
                    "911",
                    "928",
                    "boxster",
                    "cayenne",
                    "cayman",
                    "macan",
                    "panamera"
                ]
            },
            {
                make: "jaguar",
                models: [
                    "e pace",
                    "f pace",
                    "f type",
                    "jaguar",
                    "s type",
                    "x type",
                    "xe",
                    "xf",
                    "xf sportbrake",
                    "xj",
                    "xk"
                ]
            },
            {
                make: "renault",
                models: [
                    "captur",
                    "clio",
                    "espace",
                    "fluence",
                    "kangoo",
                    "koleos",
                    "lutecia",
                    "master",
                    "megane",
                    "megane estate",
                    "premium",
                    "renault truck",
                    "safrane",
                    "scenic",
                    "talisman",
                    "trafic",
                    "twingo",
                    "zoe"
                ]
            },
            { make: "scania", models: [] },
            { make: "chevrolet", models: [] },
            {
                make: "fiat",
                models: [
                    "500",
                    "500c",
                    "500l",
                    "500s",
                    "500x",
                    "fiat",
                    "freemont",
                    "grande punto",
                    "new panda",
                    "panda",
                    "punto"
                ]
            },
            {
                make: "kia",
                models: [
                    "bongo3",
                    "carens",
                    "carnival",
                    "ceed",
                    "cerato",
                    "forte",
                    "frontier",
                    "k2500",
                    "k3",
                    "k5",
                    "k7",
                    "k9",
                    "lotze",
                    "mohave",
                    "morning",
                    "niro",
                    "opirus",
                    "optima",
                    "picanto",
                    "pregio",
                    "pride",
                    "ray",
                    "rio",
                    "selots",
                    "sorento",
                    "soul",
                    "sportage",
                    "stinger",
                    "stonic",
                    "venga",
                    "visto"
                ]
            },
            {
                make: "daf",
                models: [
                    "cf",
                    "cf75 360",
                    "cf85 360",
                    "cf85 460",
                    "daf",
                    "daf truck",
                    "lf",
                    "xf",
                    "xf105 460"
                ]
            },
            {
                make: "citroen",
                models: [
                    "berlingo",
                    "c-elysee",
                    "c-zero",
                    "c1",
                    "c3",
                    "c3 picasso",
                    "c3 pluriel",
                    "c4",
                    "c4 cactus",
                    "c4 picasso",
                    "c5",
                    "citroen",
                    "ds3",
                    "ds3 crossback",
                    "ds4",
                    "ds5",
                    "grand c4 picasso",
                    "jumper"
                ]
            },
            { make: "iveco", models: ["eurocargo", "iveco"] },
            {
                make: "nissan diesel",
                models: [
                    "big thumb",
                    "condor",
                    "nissan diesel",
                    "space arrow",
                    "ud"
                ]
            },
            {
                make: "hyundai",
                models: [
                    "accent",
                    "aslan",
                    "avante",
                    "click",
                    "county",
                    "dynasty",
                    "elantra",
                    "equus",
                    "galloper",
                    "genesis",
                    "grace",
                    "grandeur",
                    "i10",
                    "i20",
                    "i30",
                    "i40",
                    "ioniq",
                    "ix20",
                    "ix35",
                    "kona",
                    "maxcruz",
                    "mighty",
                    "palisade",
                    "porter",
                    "porter ii",
                    "porter special",
                    "santa fe",
                    "solati",
                    "sonata",
                    "starex",
                    "terracan",
                    "trajet",
                    "tucson",
                    "tuscani",
                    "veloster",
                    "venue",
                    "veracruz",
                    "verna"
                ]
            },
            {
                make: "jeep",
                models: [
                    "cherokee",
                    "compass",
                    "grand cherokee",
                    "patriot",
                    "wrangler"
                ]
            },
            { make: "man", models: ["man", "tga", "tgl", "tgm", "tgs", "tgx"] },
            {
                make: "chrysler",
                models: [
                    "300",
                    "300c",
                    "cross fire",
                    "grand voyager",
                    "pacifica",
                    "voyager",
                    "ypsilon"
                ]
            },
            {
                make: "alfa romeo",
                models: [
                    "alfa 147",
                    "alfa 155",
                    "alfa 156",
                    "alfa 159",
                    "alfa gt",
                    "alfa spider",
                    "giulia",
                    "giulietta",
                    "mito"
                ]
            },
            {
                make: "maserati",
                models: [
                    "ghibli",
                    "gran turismo",
                    "grancabrio",
                    "levante",
                    "quattroporte"
                ]
            },
            {
                make: "amg",
                models: [
                    "amg",
                    "cclass",
                    "eclass",
                    "gclass",
                    "sclass",
                    "sl",
                    "slk"
                ]
            },
            {
                make: "mitsuoka",
                models: ["galue", "galue i", "himiko", "viewt"]
            },
            { make: "ud trucks", models: ["condor", "quon"] },
            {
                make: "bentley",
                models: ["bentayga", "continental", "flying spur"]
            },
            {
                make: "seat",
                models: [
                    "alhambra",
                    "altea",
                    "arona",
                    "exeo",
                    "ibiza",
                    "leon",
                    "mil",
                    "seat",
                    "toledo"
                ]
            },
            {
                make: "opel",
                models: [
                    "adam",
                    "agila",
                    "antara",
                    "astra",
                    "cascada",
                    "corsa",
                    "insignia",
                    "karl",
                    "mokka",
                    "mokka x",
                    "opel",
                    "vivaro",
                    "zafira"
                ]
            },
            {
                make: "infiniti",
                models: [
                    "g37",
                    "m35",
                    "q50",
                    "q60",
                    "q70",
                    "qx60",
                    "qx70",
                    "qx80"
                ]
            },
            { make: "abarth", models: ["500", "595", "695 edizione maserati"] },
            {
                make: "ferrari",
                models: [
                    "458 italia",
                    "458 spider",
                    "488 spider",
                    "599",
                    "612",
                    "california",
                    "f355",
                    "f430",
                    "f430 spider"
                ]
            },
            { make: "daimler", models: [] },
            {
                make: "dodge",
                models: [
                    "dodge charger",
                    "dodge nitro",
                    "durango",
                    "journey",
                    "ram"
                ]
            },
            { make: "bmw alpina", models: ["b3"] },
            { make: "rover", models: ["75", "mini"] },
            { make: "saab", models: ["93 series", "95 series"] },
            { make: "lotus", models: ["europa", "europa s"] },
            { make: "aston martin", models: ["db9", "v12 vantage"] },
            {
                make: "cadillac",
                models: [
                    "ats",
                    "concours",
                    "ct6",
                    "cts",
                    "escalade",
                    "fleetwood",
                    "srx",
                    "srx crossover",
                    "xt5 crossover"
                ]
            },
            {
                make: "skoda",
                models: [
                    "citigo",
                    "fabia",
                    "octavia",
                    "rapid",
                    "roomster",
                    "superb",
                    "yeti"
                ]
            },
            { make: "smart", models: [] },
            { make: "hummer", models: ["hummer h2", "hummer h3"] },
            { make: "tesla", models: ["model s"] },
            {
                make: "gm daewoo",
                models: [
                    "alpheon",
                    "aveo",
                    "bs106",
                    "captiva",
                    "cruze",
                    "damas",
                    "gentra",
                    "impala",
                    "labo",
                    "lacetti",
                    "malibu",
                    "matiz",
                    "orlando",
                    "spark",
                    "statesman",
                    "tosca",
                    "trax",
                    "winstorm"
                ]
            },
            {
                make: "samsung",
                models: [
                    "clio",
                    "qm3",
                    "qm5",
                    "qm6",
                    "sm3",
                    "sm5",
                    "sm6",
                    "sm7"
                ]
            },
            {
                make: "ssangyong",
                models: [
                    "actyon",
                    "chairman",
                    "korando",
                    "kyron",
                    "rexton",
                    "rodius",
                    "tivoli"
                ]
            },
            {
                make: "cat",
                models: [
                    "caterpillar",
                    "dump truck",
                    "excavator",
                    "forklift",
                    "wheel loader"
                ]
            },
            { make: "genesis", models: ["eq900", "g80"] },
            {
                make: "komatsu",
                models: [
                    "bulldozer",
                    "excavator",
                    "forklift",
                    "mini excavator",
                    "wheel loader"
                ]
            },
            { make: "jcb", models: [] },
            {
                make: "volvo construction equipment",
                models: ["excavator", "wheel loader"]
            },
            { make: "hitachi", models: ["excavator", "hitachi"] },
            { make: "doosan", models: ["excavator", "wheel loader"] },
            {
                make: "bomag",
                models: [
                    "combination roller",
                    "motor grader",
                    "vibratory roller"
                ]
            },
            { make: "dacia", models: [] },
            {
                make: "hyundai construction equipment",
                models: ["excavator", "wheel loader"]
            },
            {
                make: "lamborghini",
                models: ["aventador", "gallardo", "huracan", "murcielago"]
            },
            { make: "golden dragon", models: [] },
            { make: "john deere", models: ["tractor"] },
            { make: "lancia", models: ["delta", "ypsilon"] },
            { make: "kobelco", models: [] },
            { make: "baic", models: ["ec180", "eu260", "eu5", "ev160"] },
            {
                make: "caterpillar",
                models: ["bulldozer", "caterpillar", "wheel loader"]
            },
            { make: "yutong", models: ["yutong"] },
            { make: "daewoo", models: [] },
            { make: "lincoln", models: ["mks"] },
            { make: "gac", models: ["aion s 530", "ga5"] },
            { make: "chery", models: ["arrizo 5e", "eq1", "tiggo 3xe"] },
            { make: "dong feng", models: ["eq5044xxytbev2", "junfeng er30"] },
            { make: "europe ford", models: ["fiesta", "mondeo"] },
            { make: "yanmar", models: [] },
            { make: "zhongtong", models: [] },
            { make: "foton", models: ["auman"] },
            { make: "jiang lin", models: ["jx6581t-m4"] },
            { make: "gmc", models: [] },
            { make: "coaster", models: [] },
            { make: "wm", models: ["ex5"] },
            { make: "haige", models: ["klq6540qe5"] },
            { make: "jac", models: ["iev6-e"] },
            { make: "sino truck", models: ["howo-7"] },
            { make: "pontiac", models: ["firebird"] },
            { make: "byd", models: ["e5"] },
            { make: "gelly", models: ["emgrand ev450"] },
            { make: "gm", models: ["chevrolet trailblazer"] },
            { make: "other", models: ["h2", "other"] }
        ],
        fuel: ["Petrol", "Diesel", "LPG", "Electric", "Hybrid", "Other"],
        transmission: ["Automatic", "Manual", "CVT", "Other"],
        driving_wheels: [
            "Rear Wheel Drive",
            "Front Wheel Drive",
            "Four Wheel Drive",
            "All Wheel Drive"
        ],
        steering: ["Left Hand Drive", "Right Hand Drive", "Other"],
        condition: ["New", "Foreign Used", "Used", "Refurbished"]
    }
};
const actions = {
    pushVehicleImage({ commit }, image) {
        commit("pushVehicleImage", image);
    },
    clearVehicleImages({ commit }) {
        commit("clearVehicleImages");
    }
};
const mutations = {
    pushVehicleImage(state, image) {
        state.images.push(image);
    },
    clearVehicleImages(state) {
        state.images = [];
    }
};
const getters = {
    vehicleFormImages(state) {
        return state.images;
    },
    options(state) {
        return state.options;
    }
};

export default {
    state,
    actions,
    mutations,
    getters
};
